name: fireapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  firebase_core: ^2.10.0
  firebase_auth: ^4.6.0 
  flutter_svg: ^1.1.0



  english_words: ^4.0.0
  provider: ^6.0.0
  google_sign_in: ^6.1.0
  quickalert: 
  url_launcher: ^6.1.11
  flutter_colorpicker: ^1.0.3
  firebase_messaging: ^14.6.0
  google_fonts: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/
