// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRf3U_wFzd8teXRL1GKwjysxYU2Jycx28',
    appId: '1:811018333400:web:e87972f655810a2f6d7bad',
    messagingSenderId: '811018333400',
    projectId: 'firedetection-3880a',
    authDomain: 'firedetection-3880a.firebaseapp.com',
    storageBucket: 'firedetection-3880a.appspot.com',
    measurementId: 'G-3BR9K4G1SY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf_v9LfYGxcJQyUqPssNCg_CqcHhi4avY',
    appId: '1:811018333400:android:e8146760e57c19536d7bad',
    messagingSenderId: '811018333400',
    projectId: 'firedetection-3880a',
    storageBucket: 'firedetection-3880a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-H6pfWPn3cswukH6X4bLB_ny1wiH6ROo',
    appId: '1:811018333400:ios:1db0549e15747b1d6d7bad',
    messagingSenderId: '811018333400',
    projectId: 'firedetection-3880a',
    storageBucket: 'firedetection-3880a.appspot.com',
    iosClientId: '811018333400-8bga50vjb9kt1v0785lhrmctojl67mod.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-H6pfWPn3cswukH6X4bLB_ny1wiH6ROo',
    appId: '1:811018333400:ios:1db0549e15747b1d6d7bad',
    messagingSenderId: '811018333400',
    projectId: 'firedetection-3880a',
    storageBucket: 'firedetection-3880a.appspot.com',
    iosClientId: '811018333400-8bga50vjb9kt1v0785lhrmctojl67mod.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireapp',
  );
}
